update hdf5 to 1.10.5
Required to link with a newer version of MPI:
/home/heister/shared-
dealii/dealii-v9.1.1/tmp/unpack/hdf5-1.10.1/testpar/t_cache.c:1222:27:
error: call to ‘MPI_Address’ declared with attribute error: MPI_Address
was removed in MPI-3.0.  Use MPI_Get_address instead.

This should go into 9.1 as well.